name: Generate

on:
  push:
    branches:
      - master

generate:
  umcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate
        run: |
          echo "TODO"
