name: Merge

on:
  push:
    branches:
      - 'umcs/*'

env:
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

jobs:
  umcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ref
        uses: actions/checkout@v2

      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
          clean: false

      - name: Merge
        id: merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REMOTE: "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/rzeszot/lustapo-data.git"
        run: |
          git config user.name 'Igor'
          git config user.email 'igor.bot@users.noreply.github.com'

          git merge "${GITHUB_SHA}" --allow-unrelated-histories

          git push "${REMOTE}" HEAD:master

      - name: Slack
        if: always()
        run: |
          curl \
            -X POST \
            -H 'Content-type: application/json; charset=utf-8' \
            -H "Authorization: Bearer $SLACK_TOKEN" \
            --data '{"text": "${{ github.event_name }} ${{ steps.merge.outcome }}", "channel": "lustapo"}' \
            https://slack.com/api/chat.postMessage
